/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActiveTags: typeof import('./components/Layout/components/ActiveTags/index.vue')['default']
    Breadcrumb: typeof import('./components/Layout/components/Navbar/Breadcrumb.vue')['default']
    Dropdown: typeof import('./components/Layout/components/Navbar/Dropdown.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Index: typeof import('./components/Layout/Index.vue')['default']
    LayoutDefault: typeof import('./components/Layout/LayoutDefault.vue')['default']
    LeftTabs: typeof import('./components/Layout/components/LeftTabs.vue')['default']
    MenuChildren: typeof import('./components/Layout/components/Menu/MenuChildren.vue')['default']
    Navbar: typeof import('./components/Layout/components/Navbar/index.vue')['default']
    RightMenu: typeof import('./components/Layout/components/Menu/RightMenu.vue')['default']
    Toobar: typeof import('./components/Layout/components/Navbar/Toobar.vue')['default']
  }
}
